version: "3.1"
services:
  ur5-sim:
    image: 'universalrobots/ursim_cb3'
    container_name: ur5-sim
    ports:
      - '29999:29999'
      - '30001:30001'
      - '30002:30002'
      - '30003:30003'
      - '30004:30004'
      - '2200:22'
      - '5900:5900'
      - '6080:6080'
    volumes:
      - ./get-movement.urp:/ursim/programs/get-movement.urp